### ISSUE TITLE
arning: file_get_contents(): SSL operation failed with code 1. 

### ISSUE THREAD

**Issue by zhe1253** [yeyingorg/php_bwh_stock_checker#2]
[code]Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /www/wwwroot/www/bwg.php on line 29

Warning: file_get_contents(): Failed to enable crypto in /www/wwwroot/www/bwg.php on line 29

Warning: file_get_contents([url]https://bandwagonhost.com/cart.php[/url]): failed to open stream: operation failed in /www/wwwroot/www/bwg.php on line 29
{"title":"搬瓦工 - 即时库存检测","banner":"最新搬瓦工优惠特卖","promo":[{"code":"BWH3HYATVBJW","discount":6.5800000000000001,"name":"优惠码"},{"code":"BWHNY2022","discount":12.220000000000001,"name":"节日优惠码"}],"plans":[]}[/code]

大佬。这个错误应该如何处理？
VPS 好像安装了 openssl , php7.4 也安装了 openssl.

**Comment by yeyingorg** [comment]
你这是国内的主机还是国外的主机...？

要不试试这个文件第29行替换成

```
$stream_opts = [
    "ssl" => [
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ]
]; 

$cart = file_get_contents("https://bwh88.net/cart.php",false, stream_context_create($stream_opts));
```

试试看？(说实话我也不懂...)

**Comment by zhe1253** [comment]
$option=array('ssl'=>array('verify_peer' => false,'verify_peer_name' => false));
$cart = file_get_contents("https://bandwagonhost.com/cart.php",false,stream_context_create($option));

我也是百度搜索一下，看你给的方案差不多。现在正常了。
